# Open Telemetry (OTEL)

In [10]:
#%pip install -r ../requirements.txt

import os

from dotenv import load_dotenv

import anthropic
import phoenix as px

from phoenix.otel import register

In [11]:
session = px.launch_app()

load_dotenv()
model_name = os.getenv("MODEL_NAME") or ""
message = os.getenv("MESSAGE") or ""

tracer_provider = register(project_name="baseline", auto_instrument=True)

Existing running Phoenix instance detected! Shutting it down and starting a new instance...
⚠️ PHOENIX_COLLECTOR_ENDPOINT is set to http://localhost:6006.
⚠️ This means that traces will be sent to the collector endpoint and not this app.
⚠️ If you would like to use this app to view traces, please unset this environmentvariable via e.g. `del os.environ['PHOENIX_COLLECTOR_ENDPOINT']`
⚠️ You will need to restart your notebook to apply this change.
boto3 is installed but aioboto3 is not. To use AWS Bedrock models in Playground, install aioboto3: pip install aioboto3
Overriding of current TracerProvider is not allowed
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
DependencyConflict: requested: "crewai >= 1.10.1" but found: "crewai 0.126.0"

🌍 To view the Phoenix app in your browser, visit http://localhost:6006/
📖 For more information on how to use Phoenix, check out https://arize.com/docs/phoenix
🔭 OpenTelemetry Tracing Details 🔭
|  Phoenix Project: baseline
|  Span Processor: SimpleSpanProcessor
|  Collector Endpoint: localhost:4317
|  Transport: gRPC
|  Transport Headers: {}
|
|  Using a default SpanProcessor. `add_span_processor` will overwrite this default.
|
|  ⚠️ WARNING: It is strongly advised to use a BatchSpanProcessor in production environments.
|
|  `register` has set this TracerProvider as the global OpenTelemetry default.
|  To disable this behavior, call `register` with `set_global_tracer_provider=False`.

## Anthropic SDK

In [12]:

client = anthropic.Anthropic()

response = client.messages.create(
    model=model_name,
    max_tokens=1024,
    messages=[
        {"role": "user", "content": message}
    ]
)

response

Message(id='msg_01PijSocx7X7Xyo7rYMnqQYf', container=None, content=[TextBlock(citations=None, text='## Security Vulnerability Analysis\n\n### Code Reviewed\n```javascript\nif (user.is_admin) {\n    session.open();\n}\n```\n\n---\n\n## Vulnerabilities Found\n\n### 🔴 Critical Issues\n\n#### 1. **Client-Side Trust / Privilege Escalation**\n```javascript\n// PROBLEM: `user.is_admin` likely comes from user-controlled input\n// Attacker can simply modify:\nuser.is_admin = true; // Browser console, intercepted request, tampered JWT\n```\n**Risk:** Any user can grant themselves admin access\n\n#### 2. **No Authentication Before Authorization**\n```javascript\n// PROBLEM: Checks role without verifying identity first\n// Is this actually the user they claim to be?\n// Missing: token validation, session verification, MFA check\n```\n\n#### 3. **Missing Null/Undefined Check**\n```javascript\n// PROBLEM: If user object is null/undefined → runtime error\n// Could cause denial of service or unexpected behavior\nif (user.is_admin) { // TypeError if user is null\n```\n\n---\n\n### 🟡 Medium Issues\n\n#### 4. **Truthy Value Coercion**\n```javascript\nuser.is_admin = "false"  // Still evaluates as TRUTHY\nuser.is_admin = 1        // Passes if expecting boolean\n```\n**Fix:** Use strict comparison\n```javascript\nif (user.is_admin === true)\n```\n\n#### 5. **No Authorization Logging/Audit Trail**\n```javascript\n// PROBLEM: No record of who opened sessions, when, or from where\n// Fails compliance requirements (HIPAA, SOC2, PCI-DSS)\n```\n\n#### 6. **Vague `session.open()` Scope**\n- What permissions does this session have?\n- Does it expire?\n- Is it tied to the specific user?\n\n---\n\n## ✅ Recommended Fix\n\n```javascript\nasync function openAdminSession(userToken) {\n    try {\n        // 1. Validate user is not null\n        if (!userToken) {\n            throw new Error("No authentication token provided");\n        }\n\n        // 2. Verify identity server-side (never trust client claims)\n        const user = await verifyTokenWithAuthServer(userToken);\n\n        // 3. Strict type check on role\n        if (user.is_admin !== true) {\n            auditLog.warn(`Unauthorized admin access attempt by user: ${user.id}`);\n            throw new Error("Access denied");\n        }\n\n        // 4. Log legitimate access\n        auditLog.info(`Admin session opened by user: ${user.id} at ${new Date()}`);\n\n        // 5. Open scoped, expiring session\n        session.open({\n            userId: user.id,\n            expiresIn: "1h",\n            permissions: ["admin"],\n        });\n\n    } catch (error) {\n        handleAuthError(error); // Centralized error handling\n    }\n}\n```\n\n---\n\n## Summary Table\n\n| # | Vulnerability | Severity | Type |\n|---|--------------|----------|------|\n| 1 | Client-side role trust | 🔴 Critical | Privilege Escalation |\n| 2 | No identity verification | 🔴 Critical | Broken Authentication |\n| 3 | No null check | 🔴 Critical | Denial of Service |\n| 4 | Truthy coercion | 🟡 Medium | Logic Flaw |\n| 5 | No audit logging | 🟡 Medium | Compliance |\n| 6 | Undefined session scope | 🟡 Medium | Over-Privilege |\n\n---\n\n**Core principle violated:** [Never Trust Client Input](https://owasp.org/www-community/vulnerabilities/Improper_Input_Validation) — all authorization checks must be enforced **server-side**.', type='text')], model='claude-sonnet-4-6', role='assistant', stop_reason='end_turn', stop_sequence=None, type='message', usage=Usage(cache_creation=CacheCreation(ephemeral_1h_input_tokens=0, ephemeral_5m_input_tokens=0), cache_creation_input_tokens=0, cache_read_input_tokens=0, inference_geo='global', input_tokens=30, output_tokens=921, server_tool_use=None, service_tier='standard'))

## Claude Agent SDK

In [13]:
from claude_agent_sdk import query, ClaudeAgentOptions

responses = []
async for msg in query(
    prompt=message,
    options=ClaudeAgentOptions(model=model_name, max_turns=1)
):
    responses.append(msg)

responses

I0330 20:45:07.776728 1577127 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0330 20:45:07.785016 1586337 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(116, generation: 1)
I0330 20:45:07.785053 1586337 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(115, generation: 1)
I0330 20:45:07.785055 1586337 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(104, generation: 1)
I0330 20:45:07.825859 1577127 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0330 20:45:07.830498 1586378 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(116, generation: 1)
I0330 20:45:07.830521 1586378 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(115, generation: 1)
I0330 20:45:07.830522 1586378 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(104, generation: 1)

[SystemMessage(subtype='init', data={'type': 'system', 'subtype': 'init', 'cwd': '/Users/svespie/Code/agent-telemetry-experiment/src', 'session_id': '2349f16b-9b6a-4844-8016-d933696b0c7e', 'tools': ['Task', 'AskUserQuestion', 'Bash', 'CronCreate', 'CronDelete', 'CronList', 'Edit', 'EnterPlanMode', 'EnterWorktree', 'ExitPlanMode', 'ExitWorktree', 'Glob', 'Grep', 'NotebookEdit', 'Read', 'RemoteTrigger', 'Skill', 'TaskOutput', 'TaskStop', 'TodoWrite', 'ToolSearch', 'WebFetch', 'WebSearch', 'Write'], 'mcp_servers': [{'name': 'claude.ai Google Calendar', 'status': 'needs-auth'}, {'name': 'claude.ai Gmail', 'status': 'needs-auth'}], 'model': 'claude-sonnet-4-6', 'permissionMode': 'default', 'slash_commands': ['update-config', 'debug', 'simplify', 'batch', 'loop', 'schedule', 'claude-api', 'compact', 'context', 'cost', 'heapdump', 'init', 'pr-comments', 'release-notes', 'review', 'security-review', 'insights'], 'apiKeySource': 'ANTHROPIC_API_KEY', 'claude_code_version': '2.1.87', 'output_style': 'default', 'agents': ['general-purpose', 'statusline-setup', 'Explore', 'Plan'], 'skills': ['update-config', 'debug', 'simplify', 'batch', 'loop', 'schedule', 'claude-api'], 'plugins': [], 'uuid': 'edf058ee-3283-4cce-9812-48ad7b0bb491', 'fast_mode_state': 'off'}),
 AssistantMessage(content=[ThinkingBlock(thinking='The user wants me to scan a simple code snippet for security vulnerabilities. I can analyze this directly without any tools.', signature='EroCClsIDBgCKkB5w3nvkDWlYKxg9MdwtA9CJUaWdvv1A7Ew1blL8toki0nMygeV4yW8Sa1+aos3o0qqV64TWqdL0bcN/FHf06WDMhFjbGF1ZGUtc29ubmV0LTQtNjgAEgzuA9Zz37+DMXejZvMaDI7NhtWBWFs0q/CdlyIw6RVLiWSsF1OrswnD0jIT8nO/+YGzDN1trhZGhc2wkk+Pi8QlcfQ10x5K1G9BQxlGKowBEcgNbWBBs9j9PGMPlFM+IAKHffeHhZmjcgVXjw8ai2YLZpyIYLHyiaBP31ftpMgghQZ8O2B7KGhJm7F1GPRQox8VrnuTmQLDHXBUEUKMWAVWRbcniPq/A7Mg/X/2YUdoqWVl8ktAlELeCqZZsDqMdp+fxMCx+bpOdjRM3Oq209SpQV79VAbNOcgB98UYAQ==')], model='claude-sonnet-4-6', parent_tool_use_id=None, error=None, usage={'input_tokens': 3, 'cache_creation_input_tokens': 2062, 'cache_read_input_tokens': 7097, 'cache_creation': {'ephemeral_5m_input_tokens': 2062, 'ephemeral_1h_input_tokens': 0}, 'output_tokens': 0, 'service_tier': 'standard', 'inference_geo': 'global'}, message_id='msg_01XQFPQc2AGux4wAgLKUGGs1', stop_reason=None, session_id='2349f16b-9b6a-4844-8016-d933696b0c7e', uuid='7850cd6c-a04d-43ad-94e2-c24d3eff9027'),
 AssistantMessage(content=[TextBlock(text='## Security Vulnerability Analysis\n\nHere is a breakdown of the vulnerabilities found in the snippet:\n\n```js\nif (user.is_admin) { session.open(); }\n```\n\n---\n\n### 🔴 Critical / High Severity\n\n**1. Client-Side / Untrusted Authorization Check**\n- **Issue:** `user.is_admin` is likely sourced from a client-controlled object (e.g., a JWT payload, request body, or session variable). An attacker could manipulate this value directly (e.g., `{"is_admin": true}`) to gain elevated privileges.\n- **Fix:** Always verify admin status server-side against a trusted source (e.g., a database lookup by authenticated user ID).\n\n**2. Missing Authentication Before Authorization**\n- **Issue:** There is no check that the `user` object is *authenticated* before checking if they are an admin. If `user` can be `null`, `undefined`, or an unauthenticated guest object, the authorization check is meaningless.\n- **Fix:** Verify identity first: `if (user && user.is_authenticated && user.is_admin)`\n\n**3. Privilege Escalation via Object Tampering**\n- **Issue:** If `user` is deserialized from untrusted input (e.g., JSON, cookie), an attacker may inject `is_admin: true` through mass assignment or insecure deserialization.\n- **Fix:** Never deserialize privilege flags directly from user input. Derive roles only from server-controlled data.\n\n---\n\n### 🟡 Medium Severity\n\n**4. No Audit Logging**\n- **Issue:** There is no logging of who opened a session, when, or from where. This makes forensic investigation of unauthorized access impossible.\n- **Fix:** Log all privilege-sensitive actions: `auditLog.record(user.id, \'session.open\', context)`.\n\n**5. `session.open()` Has No Error Handling**\n- **Issue:** If `session.open()` throws, it may leave resources in an inconsistent state or leak sensitive information via unhandled exceptions.\n- **Fix:** Wrap in a `try/catch` and fail securely.\n\n---\n\n### 🟢 Recommendations Summary\n\n| # | Issue | Recommendation |\n|---|-------|----------------|\n| 1 | Untrusted `is_admin` flag | Re-verify role from DB server-side |\n| 2 | No authentication check | Check `is_authenticated` before `is_admin` |\n| 3 | Object tampering / mass assignment | Whitelist and sanitize user object fields |\n| 4 | No audit trail | Add structured logging for privilege actions |\n| 5 | No error handling | Wrap `session.open()` in try/catch |\n\n---\n\n### ✅ Hardened Example\n\n```js\ntry {\n  const trustedUser = await db.users.findById(session.authenticatedUserId);\n\n  if (!trustedUser || !trustedUser.is_authenticated) {\n    throw new Error("Unauthenticated access attempt");\n  }\n\n  if (trustedUser.is_admin) {\n    auditLog.record(trustedUser.id, "session.open", requestContext);\n    session.open();\n  }\n} catch (err) {\n  logger.error("Session open failed", { error: err.message });\n  throw new UnauthorizedError("Access denied");\n}\n```\n\nThe core principle violated here is: **never trust client-supplied authorization data — always enforce access control server-side from a trusted source.**')], model='claude-sonnet-4-6', parent_tool_use_id=None, error=None, usage={'input_tokens': 3, 'cache_creation_input_tokens': 2062, 'cache_read_input_tokens': 7097, 'cache_creation': {'ephemeral_5m_input_tokens': 2062, 'ephemeral_1h_input_tokens': 0}, 'output_tokens': 0, 'service_tier': 'standard', 'inference_geo': 'global'}, message_id='msg_01XQFPQc2AGux4wAgLKUGGs1', stop_reason=None, session_id='2349f16b-9b6a-4844-8016-d933696b0c7e', uuid='a8177b20-8a4b-4794-8308-32019936afd6'),
 ResultMessage(subtype='success', duration_ms=16593, duration_api_ms=16583, is_error=False, num_turns=1, session_id='2349f16b-9b6a-4844-8016-d933696b0c7e', stop_reason='end_turn', total_cost_usd=0.0229206, usage={'input_tokens': 3, 'cache_creation_input_tokens': 2062, 'cache_read_input_tokens': 7097, 'output_tokens': 870, 'server_tool_use': {'web_search_requests': 0, 'web_fetch_requests': 0}, 'service_tier': 'standard', 'cache_creation': {'ephemeral_1h_input_tokens': 0, 'ephemeral_5m_input_tokens': 2062}, 'inference_geo': '', 'iterations': [], 'speed': 'standard'}, result='## Security Vulnerability Analysis\n\nHere is a breakdown of the vulnerabilities found in the snippet:\n\n```js\nif (user.is_admin) { session.open(); }\n```\n\n---\n\n### 🔴 Critical / High Severity\n\n**1. Client-Side / Untrusted Authorization Check**\n- **Issue:** `user.is_admin` is likely sourced from a client-controlled object (e.g., a JWT payload, request body, or session variable). An attacker could manipulate this value directly (e.g., `{"is_admin": true}`) to gain elevated privileges.\n- **Fix:** Always verify admin status server-side against a trusted source (e.g., a database lookup by authenticated user ID).\n\n**2. Missing Authentication Before Authorization**\n- **Issue:** There is no check that the `user` object is *authenticated* before checking if they are an admin. If `user` can be `null`, `undefined`, or an unauthenticated guest object, the authorization check is meaningless.\n- **Fix:** Verify identity first: `if (user && user.is_authenticated && user.is_admin)`\n\n**3. Privilege Escalation via Object Tampering**\n- **Issue:** If `user` is deserialized from untrusted input (e.g., JSON, cookie), an attacker may inject `is_admin: true` through mass assignment or insecure deserialization.\n- **Fix:** Never deserialize privilege flags directly from user input. Derive roles only from server-controlled data.\n\n---\n\n### 🟡 Medium Severity\n\n**4. No Audit Logging**\n- **Issue:** There is no logging of who opened a session, when, or from where. This makes forensic investigation of unauthorized access impossible.\n- **Fix:** Log all privilege-sensitive actions: `auditLog.record(user.id, \'session.open\', context)`.\n\n**5. `session.open()` Has No Error Handling**\n- **Issue:** If `session.open()` throws, it may leave resources in an inconsistent state or leak sensitive information via unhandled exceptions.\n- **Fix:** Wrap in a `try/catch` and fail securely.\n\n---\n\n### 🟢 Recommendations Summary\n\n| # | Issue | Recommendation |\n|---|-------|----------------|\n| 1 | Untrusted `is_admin` flag | Re-verify role from DB server-side |\n| 2 | No authentication check | Check `is_authenticated` before `is_admin` |\n| 3 | Object tampering / mass assignment | Whitelist and sanitize user object fields |\n| 4 | No audit trail | Add structured logging for privilege actions |\n| 5 | No error handling | Wrap `session.open()` in try/catch |\n\n---\n\n### ✅ Hardened Example\n\n```js\ntry {\n  const trustedUser = await db.users.findById(session.authenticatedUserId);\n\n  if (!trustedUser || !trustedUser.is_authenticated) {\n    throw new Error("Unauthenticated access attempt");\n  }\n\n  if (trustedUser.is_admin) {\n    auditLog.record(trustedUser.id, "session.open", requestContext);\n    session.open();\n  }\n} catch (err) {\n  logger.error("Session open failed", { error: err.message });\n  throw new UnauthorizedError("Access denied");\n}\n```\n\nThe core principle violated here is: **never trust client-supplied authorization data — always enforce access control server-side from a trusted source.**', structured_output=None, model_usage={'claude-sonnet-4-6': {'inputTokens': 3, 'outputTokens': 870, 'cacheReadInputTokens': 7097, 'cacheCreationInputTokens': 2062, 'webSearchRequests': 0, 'costUSD': 0.0229206, 'contextWindow': 200000, 'maxOutputTokens': 32000}}, permission_denials=[], errors=None, uuid='df900bda-a0fc-4c45-810b-77018da83382')]

## LangChain

In [14]:
from langchain_anthropic import ChatAnthropic

llm = ChatAnthropic(model=model_name)
response = llm.invoke(message)

response

AIMessage(content='## Security Vulnerability Analysis\n\n### Code Reviewed\n```javascript\nif (user.is_admin) {\n    session.open();\n}\n```\n\n---\n\n## Vulnerabilities Identified\n\n### 🔴 Critical Issues\n\n#### 1. **Missing Authentication Check**\nThe code checks *authorization* (role) but not *authentication* (identity verification).\n```javascript\n// PROBLEM: Who confirmed this user is who they claim to be?\nif (user.is_admin) { // is_admin could be user-supplied/tampered data\n    session.open();\n}\n```\n\n#### 2. **Privilege Escalation Risk**\nIf `user` object comes from client-side input or an untrusted source, an attacker can manipulate `is_admin`.\n```javascript\n// Attack example:\nconst user = JSON.parse(request.body); // { "is_admin": true }\nif (user.is_admin) { // Trivially bypassed\n    session.open();\n}\n```\n\n#### 3. **No Input Validation**\n`is_admin` has no type enforcement — truthy values could unintentionally pass:\n```javascript\nuser.is_admin = 1;        // passes\nuser.is_admin = "yes";    // passes\nuser.is_admin = [];       // passes (truthy in JS!)\nuser.is_admin = "false";  // passes (non-empty string!)\n```\n\n---\n\n### 🟡 Medium Issues\n\n| Issue | Risk |\n|-------|------|\n| No MFA requirement | Admin access with single factor |\n| No rate limiting visible | Brute-force attacks possible |\n| No audit logging | No record of admin session opens |\n| `session.open()` undefined behavior | Unclear if sessions expire/invalidate |\n\n---\n\n### 🟢 Recommended Fix\n```javascript\nasync function openAdminSession(request) {\n    // 1. Verify authentication first\n    const user = await authenticateUser(request.token);\n    if (!user) {\n        throw new AuthenticationError("Invalid or expired token");\n    }\n\n    // 2. Strict type + value check for authorization\n    if (user.is_admin !== true) {\n        auditLog.warn(`Unauthorized admin attempt by user: ${user.id}`);\n        throw new AuthorizationError("Insufficient privileges");\n    }\n\n    // 3. Require MFA for sensitive operations\n    if (!user.mfa_verified) {\n        throw new MFARequiredError("MFA required for admin access");\n    }\n\n    // 4. Log the action\n    auditLog.info(`Admin session opened by user: ${user.id}`);\n\n    // 5. Open session with constraints\n    return session.open({\n        userId: user.id,\n        expiresIn: 3600,\n        ipBinding: request.ip\n    });\n}\n```\n\n---\n\n### Key Principles Violated\n- **Never trust client-supplied role data**\n- **Authentication must precede authorization**\n- **Strict equality checks for security flags** (`=== true`, not just truthy)\n- **Sensitive actions require audit trails**', additional_kwargs={}, response_metadata={'id': 'msg_018v3qX1dyJabqLTPrFiaR9A', 'container': None, 'model': 'claude-sonnet-4-6', 'stop_reason': 'end_turn', 'stop_sequence': None, 'usage': {'cache_creation': {'ephemeral_1h_input_tokens': 0, 'ephemeral_5m_input_tokens': 0}, 'cache_creation_input_tokens': 0, 'cache_read_input_tokens': 0, 'inference_geo': 'global', 'input_tokens': 30, 'output_tokens': 739, 'server_tool_use': None, 'service_tier': 'standard'}, 'model_name': 'claude-sonnet-4-6', 'model_provider': 'anthropic'}, id='lc_run--019d415a-37fe-73d0-8dca-60fb12155649-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 30, 'output_tokens': 739, 'total_tokens': 769, 'input_token_details': {'cache_read': 0, 'cache_creation': 0, 'ephemeral_5m_input_tokens': 0, 'ephemeral_1h_input_tokens': 0}})

## Pydantic AI

In [15]:
from pydantic_ai import Agent as PydanticAgent

agent = PydanticAgent(f"anthropic:{model_name}")
result = await agent.run(message)

result

AgentRunResult(output='## Security Vulnerability Analysis\n\n### Code Reviewed\n```javascript\nif (user.is_admin) {\n    session.open();\n}\n```\n\n---\n\n## Vulnerabilities Identified\n\n### 🔴 Critical Issues\n\n**1. Missing Authentication Verification**\n```javascript\n// PROBLEM: Only checks a property, not verified identity\nif (user.is_admin) { ... }\n\n// SAFER: Verify through trusted authentication source\nif (authService.verifyAdminRole(user.id, session.token)) { ... }\n```\n\n**2. Client-Side / Untrusted Data Trust**\n- `user.is_admin` may come from **user-controlled input**\n- An attacker could manipulate the object property directly\n- No cryptographic verification of the claim\n\n**3. No Authentication Before Authorization**\n```javascript\n// Missing: Is this user even authenticated first?\nif (!user.isAuthenticated) throw new AuthError();\nif (!authService.verifyAdminRole(user.id)) throw new AuthzError();\nsession.open();\n```\n\n---\n\n### 🟡 Medium Issues\n\n| Issue | Risk |\n|-------|------|\n| No rate limiting | Brute force attempts |\n| No audit logging | No record of admin access |\n| Boolean flag authorization | Privilege escalation via property tampering |\n| No session expiry visible | Session hijacking risk |\n\n---\n\n### 🟢 Recommended Fix\n```javascript\nasync function openAdminSession(user, token) {\n    // 1. Verify authentication first\n    if (!user || !token) throw new Error("Unauthorized");\n\n    // 2. Validate token cryptographically\n    const verified = await authService.verifyToken(token);\n    if (!verified) throw new Error("Invalid token");\n\n    // 3. Check role from SERVER-SIDE trusted source\n    const isAdmin = await db.getUserRole(verified.userId) === "admin";\n    if (!isAdmin) throw new Error("Forbidden");\n\n    // 4. Audit log\n    auditLog.record(verified.userId, "ADMIN_SESSION_OPEN");\n\n    // 5. Open session with expiry\n    session.open({ userId: verified.userId, expiresIn: "1h" });\n}\n```\n\n---\n\n## Key Principle\n> **Never trust client-supplied authorization claims. Always verify server-side from a trusted source.**')

## CrewAI

In [16]:
from crewai import Agent as CrewAgent, Task, Crew, LLM

llm = LLM(model=model_name)

agent = CrewAgent(
    role="Assistant",
    goal="Respond to the user's message",
    backstory="You are a helpful assistant.",
    llm=llm
)

task = Task(
    description=message,
    expected_output="A response to the user's message",
    agent=agent
)

crew = Crew(agents=[agent], tasks=[task])
result = crew.kickoff()

result

CrewOutput(raw='## Security Vulnerability Analysis\n\n**Code Under Review:**\n```javascript\nif (user.is_admin) {\n    session.open();\n}\n```\n\n---\n\n### 🔴 Identified Vulnerabilities\n\n---\n\n#### 1. **Insufficient Authentication / Missing Verification of Identity**\n- **Issue:** The code only checks `user.is_admin` — a client-side or untrusted property — without verifying *who* the user actually is (authentication) before checking *what they can do* (authorization).\n- **Risk:** If `user` is a mutable object that can be tampered with (e.g., via JavaScript prototype pollution, deserialization attacks, or direct client manipulation), an attacker could set `is_admin = true` trivially.\n- **Fix:** Always validate identity server-side before trusting role properties.\n\n---\n\n#### 2. **Client-Side Trust / Improper Authorization**\n- **Issue:** `user.is_admin` appears to be a flat boolean flag. If this value is derived from client-supplied input (e.g., a JWT claim that is not verified, a cookie, or a request parameter), it can be forged.\n- **Risk:** Privilege escalation — a non-admin user could open a privileged session.\n- **Fix:** Validate `is_admin` server-side against a trusted source (e.g., database lookup by authenticated user ID).\n\n---\n\n#### 3. **No Authentication Check Before Authorization**\n- **Issue:** There is no check that the user is *authenticated* before evaluating `is_admin`. If `user` can be `null`, `undefined`, or an unauthenticated object, the logic may still proceed or behave unexpectedly.\n- **Risk:** Null pointer / undefined reference exceptions, or bypassing authorization entirely if the check fails silently.\n- **Fix:**\n```javascript\nif (user && user.is_authenticated && user.is_admin) {\n    session.open();\n}\n```\n\n---\n\n#### 4. **Missing Session Security Controls**\n- **Issue:** `session.open()` is called with no visible security parameters — no timeout, no binding to IP/user-agent, no token rotation.\n- **Risk:** Session hijacking, session fixation attacks.\n- **Fix:** Ensure `session.open()` enforces:\n  - Secure, HttpOnly, SameSite cookie flags\n  - Session expiration / idle timeout\n  - Session token regeneration after privilege escalation\n\n---\n\n#### 5. **Prototype Pollution Risk (JavaScript-specific)**\n- **Issue:** In JavaScript, if `user` is a plain object `{}`, an attacker might exploit prototype pollution to set `Object.prototype.is_admin = true`, causing this check to pass for *any* user object.\n- **Fix:** Use a strict check:\n```javascript\nif (Object.prototype.hasOwnProperty.call(user, \'is_admin\') && user.is_admin === true) {\n    session.open();\n}\n```\n\n---\n\n#### 6. **No Logging or Audit Trail**\n- **Issue:** There is no logging of who opened a privileged session, when, or from where.\n- **Risk:** No forensic trail for incident response; makes detecting abuse impossible.\n- **Fix:** Log all admin session openings with timestamp, user ID, IP address, and action taken.\n\n---\n\n#### 7. **No Rate Limiting or Brute Force Protection**\n- **Issue:** If this check is in a path reachable repeatedly (e.g., an API endpoint), there\'s no indication of rate limiting.\n- **Risk:** Brute-force or automated exploitation attempts.\n- **Fix:** Apply rate limiting and account lockout policies.\n\n---\n\n### ✅ Recommended Secure Version\n\n```javascript\n// Server-side only — never trust client-supplied role flags\nconst dbUser = await UserRepository.findById(authenticatedUserId); // Fetch from trusted source\n\nif (dbUser && dbUser.is_authenticated && dbUser.is_admin === true) {\n    logger.info(`Admin session opened by user ${dbUser.id} from IP ${request.ip}`);\n    session.open({\n        secure: true,\n        httpOnly: true,\n        sameSite: \'Strict\',\n        maxAge: 3600 // 1 hour timeout\n    });\n} else {\n    logger.warn(`Unauthorized admin session attempt by user ${dbUser?.id} from IP ${request.ip}`);\n    throw new UnauthorizedError("Access denied.");\n}\n```\n\n---\n\n### 📋 Summary Table\n\n| # | Vulnerability | Severity | Fix |\n|---|--------------|----------|-----|\n| 1 | Unverified user identity | 🔴 Critical | Server-side auth check |\n| 2 | Client-side trust of `is_admin` | 🔴 Critical | DB lookup for role |\n| 3 | No authentication check | 🔴 High | Add `is_authenticated` guard |\n| 4 | Insecure session opening | 🟠 High | Add session security flags |\n| 5 | Prototype pollution (JS) | 🟠 High | Use `hasOwnProperty` check |\n| 6 | No audit logging | 🟡 Medium | Add logging |\n| 7 | No rate limiting | 🟡 Medium | Apply rate limiting |', pydantic=None, json_dict=None, tasks_output=[TaskOutput(description='Scan the following logic for vulnerabilities: if (user.is_admin) { session.open(); }', name=None, expected_output="A response to the user's message", summary='Scan the following logic for vulnerabilities: if (user.is_admin) { session.open();...', raw='## Security Vulnerability Analysis\n\n**Code Under Review:**\n```javascript\nif (user.is_admin) {\n    session.open();\n}\n```\n\n---\n\n### 🔴 Identified Vulnerabilities\n\n---\n\n#### 1. **Insufficient Authentication / Missing Verification of Identity**\n- **Issue:** The code only checks `user.is_admin` — a client-side or untrusted property — without verifying *who* the user actually is (authentication) before checking *what they can do* (authorization).\n- **Risk:** If `user` is a mutable object that can be tampered with (e.g., via JavaScript prototype pollution, deserialization attacks, or direct client manipulation), an attacker could set `is_admin = true` trivially.\n- **Fix:** Always validate identity server-side before trusting role properties.\n\n---\n\n#### 2. **Client-Side Trust / Improper Authorization**\n- **Issue:** `user.is_admin` appears to be a flat boolean flag. If this value is derived from client-supplied input (e.g., a JWT claim that is not verified, a cookie, or a request parameter), it can be forged.\n- **Risk:** Privilege escalation — a non-admin user could open a privileged session.\n- **Fix:** Validate `is_admin` server-side against a trusted source (e.g., database lookup by authenticated user ID).\n\n---\n\n#### 3. **No Authentication Check Before Authorization**\n- **Issue:** There is no check that the user is *authenticated* before evaluating `is_admin`. If `user` can be `null`, `undefined`, or an unauthenticated object, the logic may still proceed or behave unexpectedly.\n- **Risk:** Null pointer / undefined reference exceptions, or bypassing authorization entirely if the check fails silently.\n- **Fix:**\n```javascript\nif (user && user.is_authenticated && user.is_admin) {\n    session.open();\n}\n```\n\n---\n\n#### 4. **Missing Session Security Controls**\n- **Issue:** `session.open()` is called with no visible security parameters — no timeout, no binding to IP/user-agent, no token rotation.\n- **Risk:** Session hijacking, session fixation attacks.\n- **Fix:** Ensure `session.open()` enforces:\n  - Secure, HttpOnly, SameSite cookie flags\n  - Session expiration / idle timeout\n  - Session token regeneration after privilege escalation\n\n---\n\n#### 5. **Prototype Pollution Risk (JavaScript-specific)**\n- **Issue:** In JavaScript, if `user` is a plain object `{}`, an attacker might exploit prototype pollution to set `Object.prototype.is_admin = true`, causing this check to pass for *any* user object.\n- **Fix:** Use a strict check:\n```javascript\nif (Object.prototype.hasOwnProperty.call(user, \'is_admin\') && user.is_admin === true) {\n    session.open();\n}\n```\n\n---\n\n#### 6. **No Logging or Audit Trail**\n- **Issue:** There is no logging of who opened a privileged session, when, or from where.\n- **Risk:** No forensic trail for incident response; makes detecting abuse impossible.\n- **Fix:** Log all admin session openings with timestamp, user ID, IP address, and action taken.\n\n---\n\n#### 7. **No Rate Limiting or Brute Force Protection**\n- **Issue:** If this check is in a path reachable repeatedly (e.g., an API endpoint), there\'s no indication of rate limiting.\n- **Risk:** Brute-force or automated exploitation attempts.\n- **Fix:** Apply rate limiting and account lockout policies.\n\n---\n\n### ✅ Recommended Secure Version\n\n```javascript\n// Server-side only — never trust client-supplied role flags\nconst dbUser = await UserRepository.findById(authenticatedUserId); // Fetch from trusted source\n\nif (dbUser && dbUser.is_authenticated && dbUser.is_admin === true) {\n    logger.info(`Admin session opened by user ${dbUser.id} from IP ${request.ip}`);\n    session.open({\n        secure: true,\n        httpOnly: true,\n        sameSite: \'Strict\',\n        maxAge: 3600 // 1 hour timeout\n    });\n} else {\n    logger.warn(`Unauthorized admin session attempt by user ${dbUser?.id} from IP ${request.ip}`);\n    throw new UnauthorizedError("Access denied.");\n}\n```\n\n---\n\n### 📋 Summary Table\n\n| # | Vulnerability | Severity | Fix |\n|---|--------------|----------|-----|\n| 1 | Unverified user identity | 🔴 Critical | Server-side auth check |\n| 2 | Client-side trust of `is_admin` | 🔴 Critical | DB lookup for role |\n| 3 | No authentication check | 🔴 High | Add `is_authenticated` guard |\n| 4 | Insecure session opening | 🟠 High | Add session security flags |\n| 5 | Prototype pollution (JS) | 🟠 High | Use `hasOwnProperty` check |\n| 6 | No audit logging | 🟡 Medium | Add logging |\n| 7 | No rate limiting | 🟡 Medium | Apply rate limiting |', pydantic=None, json_dict=None, agent='Assistant', output_format=<OutputFormat.RAW: 'raw'>)], token_usage=UsageMetrics(total_tokens=1462, prompt_tokens=194, cached_prompt_tokens=0, completion_tokens=1268, successful_requests=1))

## Compare Traces

Pull all spans from Phoenix and compare what each instrumentor captured.

In [17]:
import time
import pandas as pd

# give the collector a moment to flush
time.sleep(2)

client = px.Client()
df = client.get_spans_dataframe(project_name="baseline")

print(f"Total spans captured: {len(df)}")
print(f"\nColumns available ({len(df.columns)}):")
for col in sorted(df.columns):
    print(f"  {col}")

Total spans captured: 12

Columns available (41):
  attributes.agent_fingerprint
  attributes.crew_agents
  attributes.crew_fingerprint
  attributes.crew_fingerprint_created_at
  attributes.crew_id
  attributes.crew_key
  attributes.crew_memory
  attributes.crew_number_of_agents
  attributes.crew_number_of_tasks
  attributes.crew_process
  attributes.crew_tasks
  attributes.crewai_version
  attributes.input.mime_type
  attributes.input.value
  attributes.llm.input_messages
  attributes.llm.invocation_parameters
  attributes.llm.model_name
  attributes.llm.output_messages
  attributes.llm.provider
  attributes.llm.system
  attributes.llm.token_count.completion
  attributes.llm.token_count.prompt
  attributes.metadata
  attributes.openinference.span.kind
  attributes.output.mime_type
  attributes.output.value
  attributes.python_version
  attributes.task_fingerprint
  attributes.task_fingerprint_created_at
  attributes.task_id
  attributes.task_key
  context.span_id
  context.trace_id
  end_time
  events
  name
  parent_id
  span_kind
  start_time
  status_code
  status_message

/var/folders/8j/f_9x77cd28703_l8b6tlflcw0000gn/T/ipykernel_45429/2486112526.py:8: DeprecationWarning: Migrate to client.spans.get_spans_dataframe() from arize-phoenix-client
  df = client.get_spans_dataframe(project_name="baseline")

In [18]:
# Show all spans with key identifying info
# Use whatever timing column exists
latency_col = next((c for c in df.columns if "latency" in c.lower() or "duration" in c.lower()), None)
cols = ["name", "span_kind", "status_code"]
if latency_col:
    cols.append(latency_col)
df[cols].reset_index(drop=True)

                    name span_kind status_code
0           Task Created   UNKNOWN          OK
1           Crew Created   UNKNOWN          OK
2   beta.messages.create       LLM          OK
3        messages.create       LLM          OK
4          ChatAnthropic       LLM          OK
5        messages.create       LLM          OK
6           Task Created   UNKNOWN          OK
7           Crew Created   UNKNOWN          OK
8   beta.messages.create       LLM          OK
9        messages.create       LLM          OK
10         ChatAnthropic       LLM          OK
11       messages.create       LLM          OK

In [19]:
# For each span, show which attribute columns are populated (non-null)
attr_cols = [c for c in df.columns if c.startswith("attributes.")]

records = []
for _, row in df.iterrows():
    populated = [c for c in attr_cols if pd.notna(row[c])]
    records.append({
        "span_name": row["name"],
        "span_kind": row["span_kind"],
        "populated_attributes": populated
    })

for r in records:
    print(f"\n=== {r['span_name']} ({r['span_kind']}) ===")
    for attr in sorted(r["populated_attributes"]):
        print(f"  {attr}")

=== Task Created (UNKNOWN) ===
  attributes.agent_fingerprint
  attributes.crew_fingerprint
  attributes.crew_id
  attributes.crew_key
  attributes.task_fingerprint
  attributes.task_fingerprint_created_at
  attributes.task_id
  attributes.task_key

=== Crew Created (UNKNOWN) ===
  attributes.crew_agents
  attributes.crew_fingerprint
  attributes.crew_fingerprint_created_at
  attributes.crew_id
  attributes.crew_key
  attributes.crew_memory
  attributes.crew_number_of_agents
  attributes.crew_number_of_tasks
  attributes.crew_process
  attributes.crew_tasks
  attributes.crewai_version
  attributes.python_version

=== beta.messages.create (LLM) ===
  attributes.input.mime_type
  attributes.input.value
  attributes.llm.input_messages
  attributes.llm.invocation_parameters
  attributes.llm.model_name
  attributes.llm.output_messages
  attributes.llm.provider
  attributes.llm.system
  attributes.llm.token_count.completion
  attributes.llm.token_count.prompt
  attributes.openinference.span.kind
  attributes.output.mime_type
  attributes.output.value

=== messages.create (LLM) ===
  attributes.input.mime_type
  attributes.input.value
  attributes.llm.input_messages
  attributes.llm.invocation_parameters
  attributes.llm.model_name
  attributes.llm.output_messages
  attributes.llm.provider
  attributes.llm.system
  attributes.llm.token_count.completion
  attributes.llm.token_count.prompt
  attributes.openinference.span.kind
  attributes.output.mime_type
  attributes.output.value

=== ChatAnthropic (LLM) ===
  attributes.input.mime_type
  attributes.input.value
  attributes.llm.input_messages
  attributes.llm.invocation_parameters
  attributes.llm.model_name
  attributes.llm.output_messages
  attributes.llm.provider
  attributes.llm.system
  attributes.llm.token_count.completion
  attributes.llm.token_count.prompt
  attributes.metadata
  attributes.openinference.span.kind
  attributes.output.mime_type
  attributes.output.value

=== messages.create (LLM) ===
  attributes.input.mime_type
  attributes.input.value
  attributes.llm.input_messages
  attributes.llm.invocation_parameters
  attributes.llm.model_name
  attributes.llm.output_messages
  attributes.llm.provider
  attributes.llm.system
  attributes.llm.token_count.completion
  attributes.llm.token_count.prompt
  attributes.openinference.span.kind
  attributes.output.mime_type
  attributes.output.value

=== Task Created (UNKNOWN) ===
  attributes.agent_fingerprint
  attributes.crew_fingerprint
  attributes.crew_id
  attributes.crew_key
  attributes.task_fingerprint
  attributes.task_fingerprint_created_at
  attributes.task_id
  attributes.task_key

=== Crew Created (UNKNOWN) ===
  attributes.crew_agents
  attributes.crew_fingerprint
  attributes.crew_fingerprint_created_at
  attributes.crew_id
  attributes.crew_key
  attributes.crew_memory
  attributes.crew_number_of_agents
  attributes.crew_number_of_tasks
  attributes.crew_process
  attributes.crew_tasks
  attributes.crewai_version
  attributes.python_version

=== beta.messages.create (LLM) ===
  attributes.input.mime_type
  attributes.input.value
  attributes.llm.input_messages
  attributes.llm.invocation_parameters
  attributes.llm.model_name
  attributes.llm.output_messages
  attributes.llm.provider
  attributes.llm.system
  attributes.llm.token_count.completion
  attributes.llm.token_count.prompt
  attributes.openinference.span.kind
  attributes.output.mime_type
  attributes.output.value

=== messages.create (LLM) ===
  attributes.input.mime_type
  attributes.input.value
  attributes.llm.input_messages
  attributes.llm.invocation_parameters
  attributes.llm.model_name
  attributes.llm.output_messages
  attributes.llm.provider
  attributes.llm.system
  attributes.llm.token_count.completion
  attributes.llm.token_count.prompt
  attributes.openinference.span.kind
  attributes.output.mime_type
  attributes.output.value

=== ChatAnthropic (LLM) ===
  attributes.input.mime_type
  attributes.input.value
  attributes.llm.input_messages
  attributes.llm.invocation_parameters
  attributes.llm.model_name
  attributes.llm.output_messages
  attributes.llm.provider
  attributes.llm.system
  attributes.llm.token_count.completion
  attributes.llm.token_count.prompt
  attributes.metadata
  attributes.openinference.span.kind
  attributes.output.mime_type
  attributes.output.value

=== messages.create (LLM) ===
  attributes.input.mime_type
  attributes.input.value
  attributes.llm.input_messages
  attributes.llm.invocation_parameters
  attributes.llm.model_name
  attributes.llm.output_messages
  attributes.llm.provider
  attributes.llm.system
  attributes.llm.token_count.completion
  attributes.llm.token_count.prompt
  attributes.openinference.span.kind
  attributes.output.mime_type
  attributes.output.value

In [20]:
# Side-by-side: which attributes does each SDK's instrumentor capture?
attr_cols = [c for c in df.columns if c.startswith("attributes.")]

summary = {}
for _, row in df.iterrows():
    name = row["name"]
    populated = {c for c in attr_cols if pd.notna(row[c])}
    if name not in summary:
        summary[name] = populated
    else:
        summary[name] |= populated

# Build a presence matrix
all_attrs = sorted(set().union(*summary.values()))
matrix = pd.DataFrame(
    {span: [attr in attrs for attr in all_attrs] for span, attrs in summary.items()},
    index=all_attrs
).replace({True: "Y", False: ""})

matrix

,Task Created,Crew Created,beta.messages.create,messages.create,ChatAnthropic
attributes.agent_fingerprint,Y,,,,
attributes.crew_agents,,Y,,,
attributes.crew_fingerprint,Y,Y,,,
attributes.crew_fingerprint_created_at,,Y,,,
attributes.crew_id,Y,Y,,,
attributes.crew_key,Y,Y,,,
attributes.crew_memory,,Y,,,
attributes.crew_number_of_agents,,Y,,,
attributes.crew_number_of_tasks,,Y,,,
attributes.crew_process,,Y,,,
attributes.crew_tasks,,Y,,,
attributes.crewai_version,,Y,,,
attributes.input.mime_type,,,Y,Y,Y
attributes.input.value,,,Y,Y,Y
attributes.llm.input_messages,,,Y,Y,Y
attributes.llm.invocation_parameters,,,Y,Y,Y
attributes.llm.model_name,,,Y,Y,Y
attributes.llm.output_messages,,,Y,Y,Y
attributes.llm.provider,,,Y,Y,Y
attributes.llm.system,,,Y,Y,Y
attributes.llm.token_count.completion,,,Y,Y,Y
attributes.llm.token_count.prompt,,,Y,Y,Y
attributes.metadata,,,,,Y
attributes.openinference.span.kind,,,Y,Y,Y
attributes.output.mime_type,,,Y,Y,Y
attributes.output.value,,,Y,Y,Y
attributes.python_version,,Y,,,
attributes.task_fingerprint,Y,,,,
attributes.task_fingerprint_created_at,Y,,,,
attributes.task_id,Y,,,,
attributes.task_key,Y,,,,